version: '3.7'

services:
    db:
        image: postgres:15.2-alpine
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
