services:
    postgres:
        image: postgres:latest
        container_name: db
        env_file:
            - .env.development
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
