services:
    app:
        build:
            context: ../../
            dockerfile: docker/production/Dockerfile
        image: jotpeee/shopcart:prod
        volumes:
            - ./:/usr/src/app
        ports:
            - '3000:3000'
