import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { getMessages, unstable_setRequestLocale } from 'next-intl/server';

import Providers from '@/components/Providers';
import { cn } from '@/lib/utils';
import { locales } from '@/navigation';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

type RootLayoutProps = {
    children: React.ReactNode;
    params: {
        locale: string;
    };
};

export const generateStaticParams = () => {
    return locales.map(locale => ({ locale }));
};

const RootLayout = async ({ children, params: { locale } }: RootLayoutProps) => {
    unstable_setRequestLocale(locale);
    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning>
            <body
                className={cn(
                    'min-h-screen bg-background font-sans antialiased',
                    fontSans.variable
                )}
            >
                <Providers locale={locale} messages={messages}>
                    {children}
                </Providers>
            </body>
        </html>
    );
};

export default RootLayout;
